### ISSUE TITLE
Main panel resize

### ISSUE THREAD

**Issue by remiheens** [eglia/ff-oc-passwords#14]
Hello, 

First, thank you for your extension, it works well, but I've a small bug, that resize main panel smaller and  smaller after each show action.

Now, my window look like this : 
![main panel](http://i.imgur.com/qqYQ0t8.png)

When I restart Firefox, the main panel start with a correct size, but after several click/show action, the main panel have this small size...

**Comment by eglia** [comment]
Hm I have seen this before, but I thought it was fixed... Can you post this information:
- version of the extension
- version of firefox
- operating system

**Comment by remiheens** [comment]
```
version of the extension : 0.3.1
version of firefox : 45.0.2
operating system : Mac OS 10.11.3
```

**Comment by remiheens** [comment]
I noticed that you have publish a new version on Firefox, so I'm running version 0.3.2 and the bug still appear

**Comment by eglia** [comment]
Okay thanks for the info. I suspect it has to do with mac os, since I haven't tested that. Unfortunately, I don't have access to a mac, but I'll try getting a Virtual Machine running.

**Comment by eglia** [comment]
Turns out getting Mac OS to run in a virtual machine is harder than expected :smile:
However, I did some improvements to the panel size handling in v0.3.3. Please let me know if this fixes your problem.

**Comment by eglia** [comment]
Closing because of no activity.
